# actions/live_writer.py
# INDUS Live Code & Notes Auto-Writer
import subprocess, sys
from datetime import datetime
from pathlib import Path

def _get_base_dir():
    if getattr(sys, "frozen", False): return Path(sys.executable).parent
    return Path(__file__).resolve().parent.parent

FILE_EXTENSIONS = {
    "python": "py", "javascript": "js", "html": "html", "css": "css",
    "markdown": "md", "notes": "md", "text": "txt", "java": "java",
    "cpp": "cpp", "sql": "sql", "json": "json", "bash": "sh"
}

def write_and_open_document(subject: str, topic: str, file_type: str = "python", player=None) -> str:
    """Generate structured code/notes, save to Desktop, open in editor."""
    if not subject or not topic:
        return "Subject aur topic dono required hain."
    from or_client import client
    ext = FILE_EXTENSIONS.get(file_type.lower(), "txt")
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{subject.replace(' ','_')}_{ts}.{ext}"
    desktop = Path.home() / "Desktop"
    desktop.mkdir(exist_ok=True)
    filepath = desktop / filename

    if ext == "py":
        header = f"# Subject: {subject}\n# Topic: {topic}\n# Generated by INDUS — {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
        system_prompt = "You are an expert Python developer. Write clean, well-commented, runnable Python code."
    elif ext in ("md", "txt"):
        header = f"# {subject}\n## {topic}\n**Date:** {datetime.now().strftime('%d %B %Y')}\n\n---\n\n"
        system_prompt = "You are an expert educator. Write clear, structured study notes with headings, bullet points, and examples."
    else:
        header = f"/* Subject: {subject} | Topic: {topic} */\n\n"
        system_prompt = f"You are an expert {file_type} developer. Write clean, well-commented {file_type} code."

    prompt = f"Write a complete {file_type} implementation for: {topic}\nContext: Subject = {subject}\nBe thorough with comments and examples."
    try:
        content = client.chat(prompt, system=system_prompt, max_tokens=2000)
    except Exception as e:
        content = f"# Generation failed: {e}\n# Please write {topic} code here."

    filepath.write_text(header + content, encoding="utf-8")

    try:
        if ext == "py" and subprocess.run(["code", "--version"], capture_output=True, timeout=3).returncode == 0:
            subprocess.Popen(["code", str(filepath)])
        else:
            subprocess.Popen(["notepad.exe", str(filepath)])
    except Exception:
        try: subprocess.Popen(["notepad.exe", str(filepath)])
        except Exception: pass

    if player: player.write_log(f"[Writer] Saved: {filename}")
    return f'"{filename}" generate ho gaya aur Desktop par save ho gaya. Editor mein open ho raha hai.'

def live_writer(parameters: dict, player=None) -> str:
    return write_and_open_document(
        subject=parameters.get("subject",""),
        topic=parameters.get("topic",""),
        file_type=parameters.get("file_type","python"),
        player=player
    )
