import re, subprocess, sys
from datetime import datetime
from pathlib import Path

def _get_base_dir():
    if getattr(sys, "frozen", False): return Path(sys.executable).parent
    return Path(__file__).resolve().parent.parent

FILE_EXTENSIONS = {
    "python": "py", "py": "py", "javascript": "js", "js": "js", "html": "html", "css": "css",
    "markdown": "md", "md": "md", "notes": "md", "text": "txt", "txt": "txt", "java": "java",
    "cpp": "cpp", "c++": "cpp", "sql": "sql", "json": "json", "bash": "sh", "sh": "sh"
}

def _clean_code_fences(content: str) -> str:
    content = content.strip()
    # Remove leading code fence like ```html or ```python
    content = re.sub(r"^```[a-zA-Z0-9_\+\-]*\n?", "", content)
    # Remove trailing code fence ```
    content = re.sub(r"\n?```$", "", content)
    return content.strip()

def write_and_open_document(subject: str = "", topic: str = "", file_type: str = "auto", player=None) -> str:
    """Generate structured code/notes, save to Desktop, open in editor."""
    raw_topic = (topic or "").strip()
    raw_subject = (subject or "").strip()

    if not raw_topic and not raw_subject:
        return "Please specify what code or document you want to create (e.g. 'Sudoku game in Python' or 'HTML portfolio page')."

    if not raw_topic:
        raw_topic = raw_subject
    if not raw_subject:
        raw_subject = raw_topic[:30].strip()

    # Smart file_type detection
    ft_lower = (file_type or "auto").lower().strip()
    combined_desc = f"{raw_subject} {raw_topic}".lower()

    if ft_lower == "auto" or ft_lower not in FILE_EXTENSIONS:
        if "html" in combined_desc or "webpage" in combined_desc or "website" in combined_desc:
            ft_lower = "html"
        elif "css" in combined_desc or "stylesheet" in combined_desc:
            ft_lower = "css"
        elif "javascript" in combined_desc or " js " in combined_desc or combined_desc.endswith("js"):
            ft_lower = "javascript"
        elif "java " in combined_desc or combined_desc.endswith("java"):
            ft_lower = "java"
        elif "c++" in combined_desc or "cpp" in combined_desc:
            ft_lower = "cpp"
        elif "sql" in combined_desc or "database" in combined_desc:
            ft_lower = "sql"
        elif "markdown" in combined_desc or "notes" in combined_desc or "study" in combined_desc:
            ft_lower = "markdown"
        else:
            ft_lower = "python"

    ext = FILE_EXTENSIONS.get(ft_lower, "py")
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    clean_name = re.sub(r"[^\w\s\-]", "", raw_subject).strip().replace(" ", "_")[:35] or "document"
    filename = f"{clean_name}_{ts}.{ext}"
    desktop = Path.home() / "Desktop"
    desktop.mkdir(exist_ok=True)
    filepath = desktop / filename

    if ext == "py":
        system_prompt = "You are an expert Python developer. Write clean, complete, runnable Python code with comments. Return ONLY the code."
        header = f"# Subject: {raw_subject}\n# Topic: {raw_topic}\n# Generated by INDUS — {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
    elif ext == "html":
        system_prompt = "You are an expert Frontend web developer. Write complete, beautiful HTML5 code with embedded CSS and modern styling. Return ONLY the HTML code."
        header = ""
    elif ext in ("md", "txt"):
        system_prompt = "You are an expert educator. Write structured, well-formatted study notes with headings, bullet points, and examples."
        header = f"# {raw_subject}\n## {raw_topic}\n**Date:** {datetime.now().strftime('%d %B %Y')}\n\n---\n\n"
    else:
        system_prompt = f"You are an expert {ft_lower} developer. Write clean, complete, runnable {ft_lower} code. Return ONLY the code."
        header = f"/* Subject: {raw_subject} | Topic: {raw_topic} */\n\n"

    prompt = f"Write a complete, high-quality, working {ft_lower} implementation for: {raw_topic}\nContext: {raw_subject}\nInclude full working logic, good design, and clear comments."
    
def _get_offline_template(subject: str, topic: str, ext: str) -> str:
    """High-quality offline code template when LLM APIs are unreachable."""
    top_lower = f"{subject} {topic}".lower()
    if ext == "html":
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{subject or 'Web Page'}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; }}
        body {{ background: #0f172a; color: #f8fafc; min-height: 100vh; display: flex; flex-direction: column; }}
        header {{ background: #1e293b; padding: 1.5rem 2rem; display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #334155; }}
        .logo {{ font-size: 1.5rem; font-weight: 700; background: linear-gradient(135deg, #38bdf8, #818cf8); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }}
        main {{ flex: 1; max-width: 1000px; margin: 2rem auto; padding: 0 1.5rem; width: 100%; }}
        .hero {{ background: linear-gradient(135deg, rgba(56, 189, 248, 0.1), rgba(129, 140, 248, 0.1)); border: 1px solid rgba(56, 189, 248, 0.2); border-radius: 1rem; padding: 3rem 2rem; text-align: center; margin-bottom: 2.5rem; }}
        .hero h1 {{ font-size: 2.5rem; margin-bottom: 1rem; color: #ffffff; }}
        .hero p {{ font-size: 1.1rem; color: #94a3b8; max-width: 600px; margin: 0 auto 1.5rem; }}
        .btn {{ background: #38bdf8; color: #0f172a; border: none; padding: 0.75rem 1.5rem; border-radius: 0.5rem; font-weight: 600; cursor: pointer; transition: all 0.2s; }}
        .btn:hover {{ background: #0ea5e9; transform: translateY(-2px); box-shadow: 0 4px 12px rgba(56, 189, 248, 0.3); }}
        .cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; }}
        .card {{ background: #1e293b; border: 1px solid #334155; border-radius: 0.75rem; padding: 1.5rem; transition: transform 0.2s; }}
        .card:hover {{ transform: translateY(-4px); border-color: #38bdf8; }}
        .card h3 {{ color: #38bdf8; margin-bottom: 0.75rem; }}
        .card p {{ color: #94a3b8; line-height: 1.6; font-size: 0.95rem; }}
        footer {{ background: #1e293b; text-align: center; padding: 1.5rem; color: #64748b; font-size: 0.875rem; border-top: 1px solid #334155; }}
    </style>
</head>
<body>
    <header>
        <div class="logo">INDUS Studio</div>
        <div><button class="btn" onclick="alert('Welcome to {subject}!')">Get Started</button></div>
    </header>
    <main>
        <section class="hero">
            <h1>{subject}</h1>
            <p>{topic}</p>
            <button class="btn" id="actionBtn" onclick="incrementCounter()">Interactive Action (Clicks: <span id="count">0</span>)</button>
        </section>
        <div class="cards">
            <div class="card">
                <h3>🚀 Fast Performance</h3>
                <p>Clean semantic HTML5 structure with optimized CSS layout and responsive mobile design.</p>
            </div>
            <div class="card">
                <h3>🎨 Modern UI/UX</h3>
                <p>Modern dark theme with glassmorphic accents, gradients, and accessible typography.</p>
            </div>
            <div class="card">
                <h3>⚙️ Interactive Scripts</h3>
                <p>Built-in vanilla JavaScript interactions ready for customization and scaling.</p>
            </div>
        </div>
    </main>
    <footer>
        &copy; {datetime.now().year} {subject}. Generated with INDUS Live Writer.
    </footer>
    <script>
        let count = 0;
        function incrementCounter() {{
            count++;
            document.getElementById('count').textContent = count;
        }}
    </script>
</body>
</html>"""

    if ext == "py" and ("sudoku" in top_lower or "game" in top_lower):
        return f'''"""
{subject} — {topic}
A complete playable Terminal Sudoku Game.
"""

def print_board(bo):
    for i in range(len(bo)):
        if i % 3 == 0 and i != 0:
            print("- - - - - - - - - - - - - ")
        for j in range(len(bo[0])):
            if j % 3 == 0 and j != 0:
                print(" | ", end="")
            if j == 8:
                print(str(bo[i][j]) if bo[i][j] != 0 else ".")
            else:
                print(str(bo[i][j]) if bo[i][j] != 0 else "." + " ", end="")

def find_empty(bo):
    for i in range(len(bo)):
        for j in range(len(bo[0])):
            if bo[i][j] == 0:
                return (i, j)
    return None

def is_valid(bo, num, pos):
    # Check row
    for j in range(len(bo[0])):
        if bo[pos[0]][j] == num and pos[1] != j:
            return False
    # Check column
    for i in range(len(bo)):
        if bo[i][pos[1]] == num and pos[0] != i:
            return False
    # Check 3x3 box
    box_x = pos[1] // 3
    box_y = pos[0] // 3
    for i in range(box_y * 3, box_y * 3 + 3):
        for j in range(box_x * 3, box_x * 3 + 3):
            if bo[i][j] == num and (i, j) != pos:
                return False
    return True

def solve_board(bo):
    find = find_empty(bo)
    if not find:
        return True
    row, col = find
    for i in range(1, 10):
        if is_valid(bo, i, (row, col)):
            bo[row][col] = i
            if solve_board(bo):
                return True
            bo[row][col] = 0
    return False

def main():
    board = [
        [7, 8, 0, 4, 0, 0, 1, 2, 0],
        [6, 0, 0, 0, 7, 5, 0, 0, 9],
        [0, 0, 0, 6, 0, 1, 0, 7, 8],
        [0, 0, 7, 0, 4, 0, 2, 6, 0],
        [0, 0, 1, 0, 5, 0, 9, 3, 0],
        [9, 0, 4, 0, 6, 0, 0, 0, 5],
        [0, 7, 0, 3, 0, 0, 0, 1, 2],
        [1, 2, 0, 0, 0, 7, 4, 0, 0],
        [0, 4, 9, 2, 0, 6, 0, 0, 7]
    ]

    print("=========================================")
    print("           SUDOKU GAME (INDUS)           ")
    print("=========================================")
    print("Initial Puzzle:")
    print_board(board)
    print("\\nSolving puzzle using backtracking...")
    solve_board(board)
    print("\\nSolved Sudoku Board:")
    print_board(board)
    print("=========================================")

if __name__ == "__main__":
    main()
'''

    if ext == "py":
        return f'''"""
{subject} — {topic}
Generated by INDUS Live Writer.
"""
import os
import sys
import time

def run():
    print(f"Executing: {subject}")
    print(f"Topic: {topic}")
    print("Initialization complete.")

if __name__ == "__main__":
    run()
'''

    return f"""/* {subject} */
/* {topic} */
// Code template generated by INDUS
console.log("Loaded {subject}");
"""

def write_and_open_document(subject: str = "", topic: str = "", file_type: str = "auto", player=None) -> str:
    """Generate structured code/notes, save to Desktop, open in editor."""
    raw_topic = (topic or "").strip()
    raw_subject = (subject or "").strip()

    if not raw_topic and not raw_subject:
        return "Please specify what code or document you want to create (e.g. 'Sudoku game in Python' or 'HTML portfolio page')."

    if not raw_topic:
        raw_topic = raw_subject
    if not raw_subject:
        raw_subject = raw_topic[:30].strip()

    # Smart file_type detection
    ft_lower = (file_type or "auto").lower().strip()
    combined_desc = f"{raw_subject} {raw_topic}".lower()

    if ft_lower == "auto" or ft_lower not in FILE_EXTENSIONS:
        if "html" in combined_desc or "webpage" in combined_desc or "website" in combined_desc:
            ft_lower = "html"
        elif "css" in combined_desc or "stylesheet" in combined_desc:
            ft_lower = "css"
        elif "javascript" in combined_desc or " js " in combined_desc or combined_desc.endswith("js"):
            ft_lower = "javascript"
        elif "java " in combined_desc or combined_desc.endswith("java"):
            ft_lower = "java"
        elif "c++" in combined_desc or "cpp" in combined_desc:
            ft_lower = "cpp"
        elif "sql" in combined_desc or "database" in combined_desc:
            ft_lower = "sql"
        elif "markdown" in combined_desc or "notes" in combined_desc or "study" in combined_desc:
            ft_lower = "markdown"
        else:
            ft_lower = "python"

    ext = FILE_EXTENSIONS.get(ft_lower, "py")
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    clean_name = re.sub(r"[^\w\s\-]", "", raw_subject).strip().replace(" ", "_")[:35] or "document"
    filename = f"{clean_name}_{ts}.{ext}"
    desktop = Path.home() / "Desktop"
    desktop.mkdir(exist_ok=True)
    filepath = desktop / filename

    if ext == "py":
        system_prompt = "You are an expert Python developer. Write clean, complete, runnable Python code with comments. Return ONLY the code."
        header = f"# Subject: {raw_subject}\n# Topic: {raw_topic}\n# Generated by INDUS — {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
    elif ext == "html":
        system_prompt = "You are an expert Frontend web developer. Write complete, beautiful HTML5 code with embedded CSS and modern styling. Return ONLY the HTML code."
        header = ""
    elif ext in ("md", "txt"):
        system_prompt = "You are an expert educator. Write structured, well-formatted study notes with headings, bullet points, and examples."
        header = f"# {raw_subject}\n## {raw_topic}\n**Date:** {datetime.now().strftime('%d %B %Y')}\n\n---\n\n"
    else:
        system_prompt = f"You are an expert {ft_lower} developer. Write clean, complete, runnable {ft_lower} code. Return ONLY the code."
        header = f"/* Subject: {raw_subject} | Topic: {raw_topic} */\n\n"

    prompt = f"Write a complete, high-quality, working {ft_lower} implementation for: {raw_topic}\nContext: {raw_subject}\nInclude full working logic, good design, and clear comments."
    
    from or_client import client
    try:
        content = client.chat(prompt, system=system_prompt, max_tokens=2500)
        content = _clean_code_fences(content)
    except Exception as e:
        content = _get_offline_template(raw_subject, raw_topic, ext)

    full_text = header + content if header and ext != "html" else content
    filepath.write_text(full_text, encoding="utf-8")

    # Open in editor
    try:
        import shutil
        code_bin = shutil.which("code") or shutil.which("code.cmd")
        if ext in ("py", "html", "js", "cpp", "java") and code_bin:
            subprocess.Popen([code_bin, str(filepath)], shell=True)
        else:
            subprocess.Popen(["notepad.exe", str(filepath)])
    except Exception:
        try:
            subprocess.Popen(["notepad.exe", str(filepath)])
        except Exception:
            pass

    if player: player.write_log(f"[Writer] Saved: {filename}")
    return f'"{filename}" generate ho gaya aur Desktop par save ho gaya. Editor me open kar diya hai.'

def live_writer(parameters: dict, player=None) -> str:
    params = parameters or {}
    return write_and_open_document(
        subject=params.get("subject", ""),
        topic=params.get("topic", "") or params.get("description", "") or params.get("prompt", ""),
        file_type=params.get("file_type", "auto"),
        player=player
    )
